### ISSUE TITLE
Support for 4.2 dropped?

### ISSUE THREAD

**Issue by darylphuah** [kodeine/laravel-meta#10]
Hey there

The recent update removed laravel 4.2 support, is there a change in the code that requires laravel 5.0/5.1? From what I can see, there doesn't seem to a reason to exclude 4.2, but I may be mistaken.

**Comment by kodeine** [comment]
@darylphuah
Ill put 4.2 back shortly.

**Comment by SUKOHI** [comment]
Please put the old version for Lavel 4.2 because now composer refuse to update all of the other packages due to laravel-meta.
Thank you in advance.
