### ISSUE TITLE
How to fetch models without any meta fields

### ISSUE THREAD

**Issue by AlirezaSedghi** [kodeine/laravel-meta#105]
Hi there,

I'm trying to load data without fetching any meta fields along with it. I've attempted to use the without method, but it's not working as expected. Here's the code I tried:

`$people = Person::without(['metas'])->get();`

Can you suggest an alternative solution or help me figure out why this approach isn't working?

Thank you.

**Comment by siamak2** [comment]
Hello
Metas are not retrieved from database by default.
They're only loaded if you either used `Model::with('metas')` or trying to access a meta.

**Comment by AlirezaSedghi** [comment]
But currently, with the eloquent query that I wrote, Laravel executed the following database queries to produce the result:

![Debugbar](https://github.com/kodeine/laravel-meta/assets/8061051/16e3a9c0-3bce-4017-ad90-f283ba22b5d3)

The picture above shows that 36500 MetaData models were loaded, using the following query for each one, even though I did not use "with('metas')":
`select * from `people_meta` where `person_id` = * and `person_id` is not null`

**Comment by siamak2** [comment]
Send the code of your eloquent query builder and how you use it's result, so I can reproduce the issue.
Does queries tab show the location and line where that query was performed?

**Comment by AlirezaSedghi** [comment]
Thanks to the helpful answers provided by @siamak2, I was able to identify the problem. The issue was caused by attempting to retrieve model attributes in the view. When attempting to retrieve a single attribute value of the model, all of its attributes were being fetched simultaneously.

**Comment by AlirezaSedghi** [comment]
Thanks to the helpful answers provided by @siamak2, I was able to identify the problem. The issue was caused by attempting to retrieve model attributes in the view. When attempting to retrieve a single attribute value of the model, all of its attributes were being fetched simultaneously.
