### ISSUE TITLE
I can't save metas in the last version of the Laravel

### ISSUE THREAD

**Issue by blackburn1911** [kodeine/laravel-meta#2]
Hey, I can't save metas when I use below code but I can update.
$post = Post::find(1);
$post->setMeta('web', 'google.ro'); OR $post->web = 'google.ro';
$post->save();

**Comment by kodeine** [comment]
@blackburn1911, please paste your post model code to look further.

**Comment by blackburn1911** [comment]
```php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laracasts\Presenter\PresentableTrait;
use Kodeine\Metable\Metable;

class Post extends Model {

    use PresentableTrait, Metable;

    protected $presenter = 'App\Presenters\PostPresenter';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'posts';

    /**
     * Many to one relation with users table
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * Many to many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }
}
```

**Comment by blackburn1911** [comment]
I think it's a problem with the saved event 

```php
protected function setObserver()
    {
        $this->saved(function ($model) {
            $model->saveMeta();
        });
    }
```

**Comment by kodeine** [comment]
@blackburn1911 

If `setMeta()` function doesnt save then it must be observer.

if saving via property doesnt work,
Can you comment out `PresentableTrait` and just leave `Metable` and try?

**Comment by blackburn1911** [comment]
Same problem hmm..

I use this code for insert:
```php
$post = Post::find(1);
$post->image = 'image/jpeg';
$post->save();
```

**Comment by kodeine** [comment]
@blackburn1911, 
$post->image is a meta right?

give me few hours and ill try to find the problem.

**Comment by blackburn1911** [comment]
Yes. I don't have image column in posts table. I want to save image to metas table.

**Comment by kodeine** [comment]
@blackburn1911 okay few hours, ill get back to you.

**Comment by blackburn1911** [comment]
Ok :+1:

**Comment by kodeine** [comment]
@blackburn1911 
Please try now, i've pushed some changes.

**Comment by blackburn1911** [comment]
Yee, it works. Now I can use $post->image = 'image for meta'; and $post->setMeta('image', 'image for meta') for save and update, but I can't use
```php
$post->setMeta([
    'content' => 'Some content here',
    'views' => 1,
]);
```
He gives me this error:
```php
PHP warning:  strtolower() expects parameter 1 to be string, array given in /home/forge/mp3loud.com/vendor/kodeine/laravel-meta/src/Kodeine/Metable/Metable.php on line 18
```

**Comment by kodeine** [comment]
@blackburn1911 
Please try now, i've pushed a fix :)

**Comment by blackburn1911** [comment]
It works. Thanks you! :heart:

**Comment by kodeine** [comment]
Glad it works :)
