### ISSUE TITLE
`getMeta` function parameter

### ISSUE THREAD

**Issue by todiadiyatmo** [kodeine/laravel-meta#21]
Hi ,
In the readme it states the `getMeta` function accept meta key params and default value.

```
$post = $post->getMeta('content', 'Something');
```

But on the code i check that the params is `key` and `raw`, is this the intended behaviour ?  using `raw` = `true` will return the meta as json

**Comment by dhcmega** [comment]
I have the same question. I think the readme is wrong.

**Comment by ArthurShlain** [comment]
How to add default return value?
