### ISSUE TITLE
Laravel 5.3 support

### ISSUE THREAD

**Issue by mheiduk** [kodeine/laravel-meta#25]
Hi,

I have upgraded from Laravel 5.2 to 5.3 and Laravel Meta stopped working. I have tested it on a fresh 5.3 installation and there is the same problem. On a fresh 5.2 installation everything works fine. There is no error notification, it just shows me the boolean false after saving and it doesn't save.

Anyone a solution for this problem?

Thanks!

best,
Marc

**Comment by Superanton** [comment]
+1

**Comment by kodeine** [comment]
@mheiduk i'll update the package asap. if you have a pr, please submit it.

**Comment by kodeine** [comment]
it supports latest laravel.
