### ISSUE TITLE
Need Eager Loading support

### ISSUE THREAD

**Issue by moyus** [kodeine/laravel-meta#28]

**Comment by darkhouse** [comment]
It's a real shame eager loading isn't supported. Otherwise this is a brilliant package. Any plans for eager loading support in the near future?

**Comment by kodeine** [comment]
@darkhouse PR's are welcome if you add that earlier than me :)

**Comment by darkhouse** [comment]
Yep. I was just curious if you were planning on handling this any time soon before I went ahead and forked it. If you're already working on it, no point in me duplicating work.

**Comment by kodeine** [comment]
@darkhouse it will take me some time to update, you can go ahead if you have time.

**Comment by darkhouse** [comment]
Myself and a colleague have been tinkering and we may have a decent solution. Needs more testing though.

**Comment by bloggervista** [comment]
@darkhouse  Please PR it . Even the author make it your idea can be great :)

**Comment by kodeine** [comment]
@darkhouse any updates?

**Comment by bloggervista** [comment]
@kodiene i guess you need to make it :) Even if he makes you can choose which is best. As i am using your package eager loading has become necessary.

**Comment by darkhouse** [comment]
Sorry for the radio silence. We've been pulled away from this part of the project. I will try and put some time in soon.

**Comment by bloggervista** [comment]
@darkhouse  i think you are not going to update if you have idea then tell me? were you gies planning to modify builder objects???

**Comment by darkhouse** [comment]
@bloggervista checkout this fork/commit https://github.com/AoumiS/laravel-meta/commit/a8daf096e9740308cbdd780f6b7c99bdc6e94736

This is my colleague's fork. We were playing around with this, but I think we ran into some trouble with it. Maybe you can take it from there.

**Comment by thequiet** [comment]
@darkhouse What problems were you running into? I was able to use the commit, but only after adding `use Illuminate\Database\Eloquent\Relations\HasMany;` to the updated Metable.php. Didn't test extensively, but the eager loading seemed to work just fine.

**Comment by rimthong** [comment]
👍 @thequiet, I forked @darkhouse 's repo, patched the missing requirement and using my repo through composer and everything looks fine. Should I make a PR?

**Comment by kodeine** [comment]
@rimthong @thequiet @darkhouse please post the PR and i'll update it.

Thanks

**Comment by thequiet** [comment]
@kodeine @rimthong @darkhouse - much appreciated.

**Comment by kodeine** [comment]
@rimthong @darkhouse @thequiet 
please upgrade and let me know if it fixes this issue.

**Comment by darkhouse** [comment]
Hey thanks for the update. Sorry about the long silence. Been away from this for some time. Excited to try this out though.

**Comment by rimthong** [comment]
Yup, looking good :) thanks!

**Comment by plivius** [comment]
@kodeine @rimthong @darkhouse @thequiet 
I happened to run into a similar eager-loading issue and thought I'd share my findings with anyone running into this as well:

Consider a query on metable-model "Role" in a nested m2m-relation, e.g. `User <=> Roles => RoleMetas`, and observe that the way (temporary) pivot-attributes are unset here:
https://github.com/illuminate/database/blob/master/Eloquent/Relations/BelongsToMany.php#L658

triggers an "unset" of mentioned pivot-attribute here:
https://github.com/kodeine/laravel-meta/blob/master/src/Kodeine/Metable/Metable.php#L307

thus creating unwanted "N+1" queries (on top of the correctly executed eager-loading aggregate-query).

**Comment by thequiet** [comment]
@kodeine, I was using a fork with eager-loading, switched to your upgraded version and everything still works perfectly. Thanks for the merge and this wonderful code, much appreciated.

**Comment by kodeine** [comment]
@plivius is this related to #37?

**Comment by plivius** [comment]
@kodeine Exactly that! I'll follow up in that thread with a proposed workaround
