### ISSUE TITLE
scopeMeta should use $this->getTable() instead of $this->table

### ISSUE THREAD

**Issue by eswinfen** [kodeine/laravel-meta#29]
The scopeMeta function uses the table member $this->table, which is only set if there is an explicit override of the table name on a model. Instead it should use the $this->getTable() method and getQualifiedKeyName() method. 

If the scopeMeta method is altered as follows it should work in all cases:

```
public function scopeMeta($query)
{
        return $query->join($this->getTable(), $this->getQualifiedKeyName(), '=', $this->getMetaTable().$this->getMetaKeyName())
            ->select($this->getTable().'.*');
}
```

**Comment by kodeine** [comment]
@eswinfen can you please propose a PR for this?

**Comment by kodeine** [comment]
@necenzurat can you please post a PR as well?

Thanks

**Comment by necenzurat** [comment]
due to the lack of inactivity, I thought you where dead and [made a fork](https://github.com/necenzurat/eloquent-meta/)

**Comment by shmuelgutman** [comment]
+1
I get `Base table or view not found`

**Comment by kodeine** [comment]
@necenzurat please post a PR and i'll merge it right away

**Comment by necenzurat** [comment]
@kodeine no, i cannot, because i did not Github Fork your repo.

**Comment by kodeine** [comment]
fixed.
