### ISSUE TITLE
A new problem, I think

### ISSUE THREAD

**Issue by blackburn1911** [kodeine/laravel-meta#3]
Hi again,

This time, I want to add posts with metas. How can I attach metas to a new post? Or this package is just for update, because I can create a Model just for Metas or I can update metas when I add a new post, in same query.

**Comment by kodeine** [comment]
@blackburn1911 this problem is fixed by your pull request right?

**Comment by blackburn1911** [comment]
This problem has been solved with this pull https://github.com/kodeine/laravel-meta/pull/6
