### ISSUE TITLE
Eager loading problem

### ISSUE THREAD

**Issue by dneykov** [kodeine/laravel-meta#37]
Hi,
after updating to the latest version of this package I'm trying to use eager loading method but when I use it the meta data is selected twice. I'm using debugbar to check the queries.

Here is snippet of debugbar:

![screen shot 2017-11-10 at 9 38 15 am](https://user-images.githubusercontent.com/5511034/32647671-1eb6f792-c5fb-11e7-9687-aabe456286ef.png)

**Comment by kodeine** [comment]
@vortechron @rimthong can you please take a look at this.

**Comment by plivius** [comment]
@dneykov Are the models in your snippet being queried via a m2m relation (BelongsToMany)?

**Comment by dneykov** [comment]
@plivius yes, I'm selecting specific role and getting all users for that row.
```
Role::find(1)->users()->with('metas')->get();
```

`users()` method is `belongsToMany` relation

**Comment by vortechron** [comment]
current eager loading only support hasMany

**Comment by dneykov** [comment]
@vortechron `belongsToMany ` relation is between `Role::class` and  `User::class` 
When I try to eager load `metas()` relationship they are loaded twice.

**Comment by plivius** [comment]
@dneykov @vortechron 
I ran into the exact same problem when querying a BelongsToMany-relation: The pivot-attributes which are "set" and "unset" by Eloquent trigger an unwanted "unset" on each of your metable models resulting in mentioned N+1 problem (also see https://github.com/kodeine/laravel-meta/issues/28#issuecomment-343308147).

I implemented a workaround for this: https://github.com/plivius/laravel-meta/commit/4aebd9d71d088250f1801b425246faedfa2999d6
@kodeine If you like/agree I can submit a PR?

**Comment by dneykov** [comment]
@plivius I just test your workaround and it's working.

**Comment by kodeine** [comment]
@plivius yes please post PR. thanks in advance :)

**Comment by plivius** [comment]
@kodeine Ok!
@dneykov Nice! Observe that the only (minor) drawback of this solution is, that unsetting meta keys prefixed with `pivot_` now becomes slightly compromised:
```
unset($model->pivot_foo_bar);
```

**Comment by kodeine** [comment]
thanks, its merged!
