### ISSUE TITLE
Unnecessary where clause on collection

### ISSUE THREAD

**Issue by dneykov** [kodeine/laravel-meta#38]
I think this where can be removed because the relationship method already gets model specific meta.
I get problem with that where because depending on the environment returned collection fields which must be int (e.g foreign key) are casted to string and this where returns null.

https://github.com/kodeine/laravel-meta/blob/70d02d9f5adc5422738bba8b1955e0f4c597d1ab/src/Kodeine/Metable/Metable.php#L214-L233 

https://github.com/laravel/framework/issues/11780

**Comment by kodeine** [comment]
@dneykov can you please post a PR and making sure it has a backwards compatibility and does not crash previous releases?

**Comment by dneykov** [comment]
@kodeine If I find some time these days I will post a PR.
About backwards compatibility I don't think it's going to crash. Previous releases are using `getModelStub()` which returns Eloquent model and where clause will work without problem there.
