### ISSUE TITLE
Use Models attributes

### ISSUE THREAD

**Issue by ray1618** [kodeine/laravel-meta#4]
I have a Item model and I want to add a new Item to it in the database.
When I try to create an attribute within the model it will be added as Meta attribute.
My model contains an 'title' colmn in the database

// when I create a new item it will store 'title' as  meta data and leave the 'title' in my model empty
$item = new Item;
$item->title = 'Blaat2';
$item->save();

result : title will be added as a meta value, title in model will be empty

// When i already stored my item and edit the value like this it works:
$item = Item::find(1);
$item->title = 'Blaat2';
$item->save();

result: now it works. The title attribute of Item will be stored

I'm using the latest version of Laravel, any way I can fix this?

**Comment by blackburn1911** [comment]
Hey,

You can create something like:
```php
$item = new Item;
$item->title = 'Blaat2';
$item->save();

if (Input::has('metas')) {
    $item = Item::find($item->id);
    $item->meta_title = 'Website';
    $item->save();
}
```
metas will be ```html <input type="text" name="metas[meta_title]">```

**Comment by ray1618** [comment]
But I don't want to store it in meta, I want to store it in the 'title' of the Item model itself

**Comment by blackburn1911** [comment]
Uhh, my mistake. It's a problem in package or it's not implemented this option.

**Comment by blackburn1911** [comment]
I sent a pull request with solved problem.

**Comment by ray1618** [comment]
Awesome thx.  I will check it out later tonight.

**Comment by ray1618** [comment]
When I was checkin your pull  request I saw that in the original __set() method that the orgininal hasColumn check was commented out @ line 326. 
I uncommented this & put a pull request for this.
Thanx for the help @blackburn1911, the problem is fixed now :)
