### ISSUE TITLE
Can't retrieve with eager loading

### ISSUE THREAD

**Issue by wigogeoffrey** [kodeine/laravel-meta#40]
Hi guys,

I'm trying to use the eager load in my laravel project. I have a Term table with his meta table.
When i do this :  

`$terms = Term::with(['metas'])->get();`

I have an error which is saying that the relationship "metas" doesn't exist. Which is true because i dont have a function "metas" in my model. But i don't know what to put inside this function "metas". 

Can you help me ?
Thanks

**Comment by dhcmega** [comment]
Hi
I have the same problem, have you solved it?

**Comment by Matoto2** [comment]
Hi, I have the same problem. Maybe someone knows how to solve this?
