### ISSUE TITLE
Scope is no longer using meta table

### ISSUE THREAD

**Issue by pridit** [kodeine/laravel-meta#41]
The b65ca6b7d65441ccbfa85ed3206cb97e2a38afea commit has caused the scope to no longer select the meta table. As a result I have any queries trying to join in on itself causing major issues. I don't see anything different in the documentation that I am not using in the model.

Can this please be resolved/reverted, or is there a different implementation I am missing to restore this to a working state?

**Comment by kodeine** [comment]
Thanks, its merged.
