### ISSUE TITLE
What's the purpose of "type" in the table schema?

### ISSUE THREAD

**Issue by ERROPiX** [kodeine/laravel-meta#43]
What's the purpose of "type" in the table schema?
I think it's better to handle this as WordPress do, without fixing the type of the value

**Comment by userabuser** [comment]
The purpose of the `type` column in your `*_meta` table is to describe the type of content being stored prior to serialisation/encoding/transformation so that when you retrieve the meta data, you get back the content in which you stored in the format in which you supplied it.

For instance if you store a DateTime object, it will store the resulting object as a string, but upon retrieval it will return you a DateTime object.

**Comment by ERROPiX** [comment]
Ok, What's the maximum length, do it really need to be varchar(255) ?

**Comment by userabuser** [comment]
Unlikely needs to be 255... the longest type names are `datetime` and `in_array`. Theoretically that does not prevent you from adding your own types that perform different unpacking, but that is more of a special case than the norm.

**Comment by ERROPiX** [comment]
Ok, I didn't tried to see what types are in the db, but what will be the strings if I passed an object instance of a class with long name name space like \Some\Very\Long\Name\Space\Provider\Class?

will it store the full class path and recreate the object upon retrieval?

**Comment by userabuser** [comment]
As per: https://github.com/kodeine/laravel-meta/blob/25823cd786e0ea1b6b5f34a10cb74e96ff2c6955/src/Kodeine/Metable/MetaData.php#L52

If it is an Eloquent model, it is stored as a string in either format,

- Class Name
- Class Name + Hash Symbol +  Model getKey() value
- On retrieval, you will get back an instance of your model

If it is an object other than an Eloquent Model, 

- it is JSON encoded.
- On retrieval, you will get an instance of `stdClass`

Setting: 

```php
    public function setValueAttribute($value)
    {
        $type = gettype($value);
        if (is_array($value)) {
            $this->type = 'array';
            $this->attributes['value'] = json_encode($value);
        } elseif ($value instanceof DateTime) {
            $this->type = 'datetime';
            $this->attributes['value'] = $this->fromDateTime($value);
        } elseif ($value instanceof Model) {
            $this->type = 'model';
            $this->attributes['value'] = get_class($value).(!$value->exists ? '' : '#'.$value->getKey());
        } elseif (is_object($value)) {
            $this->type = 'object';
            $this->attributes['value'] = json_encode($value);
        } else {
            $this->type = in_array($type, $this->dataTypes) ? $type : 'string';
            $this->attributes['value'] = $value;
        }
    }
```

Getting: 
```php
    public function getValueAttribute($value)
    {
        $type = $this->type ?: 'null';
        switch ($type) {
            case 'array':
                return json_decode($value, true);
            case 'object':
                return json_decode($value);
            case 'datetime':
                return $this->asDateTime($value);
            case 'model': {
                if (strpos($value, '#') === false) {
                    return new $value();
                }
                list($class, $id) = explode('#', $value);
                return with(new $class())->findOrFail($id);
            }
        }
        if (in_array($type, $this->dataTypes)) {
            settype($value, $type);
        }
        return $value;
    }
```

**Comment by ERROPiX** [comment]
Ok, I close this as it's not an issue
