### ISSUE TITLE
Feature Request: Default Values

### ISSUE THREAD

**Issue by benyanke** [kodeine/laravel-meta#45]
Currently, I have a situation where I need to note if a user is, for example, out sick for the day. 

Of course, the logical way to store this using this plugin would be to only store rows for sick users (since any individual user would rarely be sick). This allows us to reduce DB bloat.

However, to do this, I have to write custom mutators and accessors which will unset the row if the meta value is being set to the default value, and will return the default value if the row does not exist.

Currently:

```

    public function setArtistactiveMeta($value)
    {

        $default = true;
        if($value == $default) {
          $this->unsetMeta('artistactive');
        } else {
          $this->setMeta('artistactive', $value);
        }
        $this->save();

    }


    public function getArtistactiveMeta()
    {
        $default = true;
        $value = $this->getMeta('artistactive');
        if(is_null($value)) {
          return $default;
        } else {
          return $value;
        }

    }
```
This isn't horrible for one attribute, but if I was going to add ten attributes with defaults... it gets messy.

This seems like something that could be added into the package, perhaps with a syntax like:
```
   protected $metaDefaults = [
       'artistactive' => 'true',
   ];
```

Thoughts?

**Comment by kodeine** [comment]
This just adds more complexity for no reason.

**Comment by benyanke** [comment]
...while also making the implementation far more DRY


Do you have a problem with the implementation or the concept?

If you dislike the concept, I'll gracefully bow out, but if you don't like the implementation, I'd be happy to chat more about it. I'm specifically using this package for values which are set to their default 80-90% of the time, so it makes things far simpler for my use.

**Comment by benyanke** [comment]
Merged:

https://github.com/kodeine/laravel-meta/pull/46
