### ISSUE TITLE
whereMeta should be static

### ISSUE THREAD

**Issue by dhcmega** [kodeine/laravel-meta#49]
Hi!
I think whereMeta should be static, so you can do something like:

`
$posts = Post::whereMeta($key, $value);
`

```
    /**
     * Query Meta Table functions
     * -------------------------.
     */
    public function whereMeta($key, $value)
    {
        return $this->getModelStub()
            ->whereKey(strtolower($key))
            ->whereValue($value)
            ->get();
    }
```

Thanks!

**Comment by kodeine** [comment]
Sounds good, can you please submit a PR?

**Comment by dhcmega** [comment]
Hi @kodeine , trying to do this now, I need some help if possible:
Changes:
```
    public static function whereMeta($key, $value)
    {
        return $this->getModelStub()
            ->whereKey(strtolower($key))
            ->whereValue($value)
            ->get();
    }
```
to:
```
    public static function whereMeta($key, $value)
    {
        $model = self::getModelStub();

        return $model->whereKey(strtolower($key))
            ->whereValue($value)
            ->get();
    }
```

Problems:
1)
whereKey generates where id = x, not where key = x, how come?
`select * from `accounts_meta` where `accounts_meta`.`id` = 'some_key' and `value` = 5`
2)
getModelStub also should be static, so `$this->metaTable` should be static. But I cannot find how to populate it. The table attribute of the model is not static. Also would not now how to get it. Maybe I can get the actual model somehow instantiate it and get the table name?
```
    protected static function getModelStub()
    {
        // get new meta model instance
        $model = new \Kodeine\Metable\MetaData();
        $model->setTable($this->metaTable);

        // model fill with attributes.
        if (func_num_args() > 0) {
            array_filter(func_get_args(), [$model, 'fill']);
        }

        return $model;
    }
```

I hope you find time to give me some guidance.
Thanks!
