### ISSUE TITLE
specify attribute list in eager loading

### ISSUE THREAD

**Issue by mira-thakkar** [kodeine/laravel-meta#50]
`$post = Post::with(['metas'])->get();`
here can we specify the list of meta attributes to return instead of returning all the attributes?

**Comment by siamak2** [comment]
This can be done according to laravel [documentation](https://laravel.com/docs/master/eloquent-relationships#constraining-eager-loads):
```php
use Illuminate\Contracts\Database\Eloquent\Builder;

$post = Post::with(['metas' => function (Builder $query) {
  $query->whereIn( 'key' , [ 'meta1' , 'meta2' ] );
}])->get();
```
Just make sure you include all the metas you're going to work with. If you forgot to include an existing meta and try to set it, it will result in duplicate meta keys in database.
