### ISSUE TITLE
Different branch or release for diff PHP version

### ISSUE THREAD

**Issue by ahsankhatri** [kodeine/laravel-meta#54]
Since many of them are still using PHP < 7 and recent commit #52 made it for PHP 7 only, please add support for PHP 7 on a different branch so that no conflict shall occur.

My old project has 5.6 and i had to use `dev-master#d3b53b8464de55a4e7cdafd25c5000f74452c759` in my `composer.json` file

Thanks.

**Comment by lrfahmi** [comment]
#55

**Comment by lrfahmi** [comment]
> Since many of them are still using PHP < 7 and recent commit #52 made it for PHP 7 only, please add support for PHP 7 on a different branch so that no conflict shall occur.
> 
> My old project has 5.6 and i had to use `dev-master#d3b53b8464de55a4e7cdafd25c5000f74452c759` in my `composer.json` file
> 
> Thanks.

I have fixed it so that it is still compatible with the old PHP version with this PR #55 . The problem is that PHP version 5 doesn't support if shorthand (?? operator).

I hope this helps.

**Comment by lrfahmi** [comment]
> Since many of them are still using PHP < 7 and recent commit #52 made it for PHP 7 only, please add support for PHP 7 on a different branch so that no conflict shall occur.
> 
> My old project has 5.6 and i had to use `dev-master#d3b53b8464de55a4e7cdafd25c5000f74452c759` in my `composer.json` file
> 
> Thanks.

I have fixed it so that it is still compatible with the old PHP version with this PR #55. The problem is that PHP version 5 doesn't support if shorthand (?? operator).

I hope this helps.
Closes #55

**Comment by lrfahmi** [comment]
Closed #55
