### ISSUE TITLE
Possibility to disable fluent getters and setters

### ISSUE THREAD

**Issue by PayteR** [kodeine/laravel-meta#59]
Is there possibility to disable flutent getters and setters? I want to call meta explicitly with getMeta(), setMeta()

**Comment by kodeine** [comment]
you dont need to disable them, just use getMeta and setMeta?

**Comment by siamak2** [comment]
As of laravel meta 2, you can disable it by adding this to your model:
```php
protected $disableFluentMeta = true;
```
