### ISSUE TITLE
Save meta 

### ISSUE THREAD

**Issue by blajanadrian18** [kodeine/laravel-meta#60]
It is possible to save the meta with the created method?

```
$post = Post::find(1);
$post->setMeta('content', 'Some content here');
$post->create($request->all);
```

**Comment by siamak2** [comment]
I tried to add this in version 2 but I had to override some of Laravel's methods and it would decrease Laravel's security. That why I decided to not implement this feature.
In `create` method Laravel  explicitly checks for table's columns, `$fillable` and `$guarded` properties to decide what to insert for security reasons.
