### ISSUE TITLE
laravel 6 support

### ISSUE THREAD

**Issue by siamak2** [kodeine/laravel-meta#65]
I can't update to laravel 6 because composer is telling me:
kodeine/laravel-meta dev-master requires illuminate/support ~5.0|~5.1
and tells me to remove this package or don't update to laravel 6

**Comment by kodeine** [comment]
Please try again and let me know if the issue is resolved?

**Comment by siamak2** [comment]
I'm still having problem.
I removed this package and upgraded to laravel 6.
then added this to composer.json:
"kodeine/laravel-meta": "master"
and run composer install and nothing happened. composer meesage:
Nothing to install or update
then I tried: composer require kodeine/laravel-meta:master
composer message:
Problem 1
    - Installation request for kodeine/laravel-meta master -> satisfiable by kodeine/laravel-meta[dev-master].
    - Conclusion: remove laravel/framework v6.0.4

composer tries to require dev-master branch but I want master branch which is compatible with laravel 6

**Comment by siamak2** [comment]
I guess this happens because package is not updated in packagist
https://packagist.org/packages/kodeine/laravel-meta
in packagist it's still doesn't support laravel 6

**Comment by siamak2** [comment]
I put:
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/kodeine/laravel-meta"
        }
    ]
to composer.json and then run composer require kodeine/laravel-meta:master and installed without error.
you should add "laravel/helpers" package as dependency because I got error: "undefined function camel_case" and this function is now available at "laravel/helpers" package
