### ISSUE TITLE
I cannot use laravel-meta in laravel 6 ?

### ISSUE THREAD

**Issue by Ladinstar** [kodeine/laravel-meta#68]
![image](https://user-images.githubusercontent.com/22459993/69487304-c9466980-0e57-11ea-8bec-81750f064796.png)
I have install this package in my laravel 6 project.
Here is the model that i want to use for
`<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Permissions\HasPermissionsTrait;
use Laravel\Passport\HasApiTokens;

use Kodeine\Metable\Metable;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait, HasApiTokens;
    
    use Metable;

    protected $metaTable = 'users_meta';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}
`
I respect all steps that you ask to install it but i have this error. Do you know why and how i can do to resolve this problem ? Thank You !

**Comment by guney** [comment]
String helpers and the other ones are removed from the Laravel core repository and moved into [laravel/helpers](https://github.com/laravel/helpers) repository as a dependency. Simply run `composer require laravel/helpers` to let laravel-meta to continue using helpers like `camel_case`.
