### ISSUE TITLE
Get meta where key contains

### ISSUE THREAD

**Issue by FourStacks** [kodeine/laravel-meta#7]
First up, thanks very much for taking the time to develop and release this package - just started using it but it's looking like a very useful tool indeed.

I was wondering if you had any plans to include a method that would allow a query to get all meta for an entity where the key contains a certain string?  Not sure if this might be considered a bit 'edgy' but I've run into a situation where I need to save meta data for a model where the individual pieces of metadata need to be unique yet must all relate to one another and should be able to be queried as a group.

I'm dealing the the uniqueness by saving input (which by default is in an array) and changing the array keys to unique keys using uniqid() and a prefix e.g. 

location_mYr4nd0mIdent1fi3r
location_4noth3rRand0mIden

Each key value pair would then be saved as separate metadata but I'd like to be able to find them as a group by their shared prefix.

I'll probably be cooking up a solution for my project anyway but thought I'd check to see if you had any plans for something similar.  If my solution can be made to fit the package then happy to do a PR if I have time and if you think it would be a useful addition?

**Comment by kodeine** [comment]
@fourstacks

I was planning to add that feature myself but didn't get enough time to play with it.  Though there is a function which I didn't put in documentation yet

public function whereMeta($key, $value)

Maybe this can help or feel free to propose pr.

**Comment by FourStacks** [comment]
I noticed that method this afternoon when I started integrating the trait.  Could be a useful starting point for what I'm after.  Will report back if I come up with anything useful.

Thanks again - awesome work!

**Comment by kodeine** [comment]
@FourStacks 

That was just a simple test function, but i was thinking to take it another level by extending query builder and then where(), limit() etc all methods will come into play with meta. 

You're welcome :)
