### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by dhcmega** [kodeine/laravel-meta#73]
Hi! how can I install it with laravel 7? thanks!

**Comment by eduardoarandah** [comment]
I took a quick look at the code and it looks fine for laravel 7, nothing mentioned in upgrade guide

https://laravel.com/docs/7.x/upgrade

I made the pull request:

https://github.com/kodeine/laravel-meta/pull/74

meanwhile, you can use my fork like this:

- in composer.json add a section "repositories" and then change version to "dev-master"

```
    "repositories": [
      {
        "type": "vcs",
        "url" : "https://github.com/eduardoarandah/laravel-meta"
      }
    ],
    "require": {
         ....
        "kodeine/laravel-meta": "dev-master",
        "laravel/framework": "^7.0",
         ....
    },
```

- remove composer.lock 
- composer install

dont forget to check the upgrade guide, you'll likely will also have to change this file in your codebase:

https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php

**Comment by dhcmega** [comment]
@eduardoarandah Thank you very much for responding and helping!!

**Comment by kodeine** [comment]
its merged! thanks guys.
