### ISSUE TITLE
Choice of table for posts_meta and not models_meta?

### ISSUE THREAD

**Issue by acip** [kodeine/laravel-meta#85]
Hi!

I find it quite misleading in terms of naming for the table -`posts_meta`. Is any reason to have it like this and not something more general like `models_meta`?

**Comment by siamak2** [comment]
Hi.
Each model has it's own meta table. for your `Post` model it's `posts_meta`, for your `User` model it's `users_meta`.
Of course you can use whatever name you like as long as you add it's name to your model:
```php
protected $metaTable = 'custom_meta_table';
```
