### ISSUE TITLE
getMetaTable and getMetaKeyName should be public

### ISSUE THREAD

**Issue by goodevilgenius** [kodeine/laravel-meta#86]
Since the eloquent functions `getTable` and `getKeyName` are public, the corresponding meta functions should also be.

This will make it easier to make meta queries outside of the model. Currently, this is impossible outside of the class context:

```php
$metaTable = (new Post)->getMetaTable();
Post::meta()->query(function ($query) use ($metaTable) {
    $query->where("$metaTable.name", 'key')->where("$metaTable.value", 'value');
});
```

**Comment by kodeine** [comment]
Can you submit PR?

**Comment by goodevilgenius** [comment]
@kodeine Sure. That's a pretty simple change. I can submit one later today.
