### ISSUE TITLE
Issues with accessors & mutators?

### ISSUE THREAD

**Issue by jumpstartcarrie** [kodeine/laravel-meta#89]
I am unable to use accessors or mutators in a model class if I include the metable trait.  They either get ignored completely, or an error is returned from the metable class (because it checks if the property exists on the model or metadata table and throws an error if not).

I could probably extend the metable class and prevent the __get and __set methods from attempting to transform an attribute into metadata if an accessor method exists in the model, but wondered if there was already a way around this, or if it's something that can be fixed in the metable class itself?

**Comment by kodeine** [comment]
Did you create the meta table needed?

**Comment by jumpstartcarrie** [comment]
I did and it works as expected, it's just that a similar process exists between accessing or creating a property as metadata from a model and accessing or saving an attribute via accessors/mutators, so I wondered if there was a fix, or something I had missed to get the two to work together nicely.
