### ISSUE TITLE
Undefined property: App\Models\User::$metaData

### ISSUE THREAD

**Issue by Zyles** [kodeine/laravel-meta#9]
Hi,

Using your package for my meta data which works great. However I run into issues when I try to add more traits and stuff to my user model.

This is my setup:

- User model with your Metable added (works as expected)
- A trait called AccountBalance which I added after yours which consists of:

```
trait AccountBalance
{
    public function scopeGetAccountBalance($query)
    {
        return $query->orderBy('id', 'DESC')->first()->pluck('balance');
    }

}

```

- My controller which is called from my route:
```
public function getAccountBalance(Request $request, $id)
    {
        $response = User::getAccountBalance()->find($id);

        return $response;
    }
```

This results in the error
```
Undefined property: App\Models\User::$metaData
```

I can't figure out why.

Thanks.

P.S. can this be caused by the fact that the account balance is in another SQL table which does not have meta data relationships?

**Comment by Zyles** [comment]
Nevermind. I refactored my code and got it working now.

**Comment by minulislam** [comment]
I am also facing this problem

https://imgur.com/a/jGJG1Bf

@Zyles 
Man can you tell me the solution please?

**Comment by Zyles** [comment]
I can't remember. I don't use this package anymore.

**Comment by kevmul** [comment]
To anyone that finds themselves here, here is something you can try :)

My issue was because I was using a `leftJoin` on my Laravel model. Simply just changed this to use the Laravel eager loading to get the same result. 

Code was 
```
Warranty::leftjoin('customers', 'warranties.customer_id', '=', 'customers.id')->select( <all my columns > );
```

New Code is
```
Warranty::with('customer');
```
Hope this helps!
