### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by Temepest74** [kodeine/laravel-meta#92]
During some tests, the saveMeta() function won't be called.

I think it is due to `self::$_isOververRegistered` being always true, and I really think this should not be the case because, during some tests, the function getListener (from vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php line 248) won't return any listeners, but sometimes will.

If you need a demo project of this bug, I could create one, I just hope that this package is still maintained. 
I solved this error for myself by treating `$_isObserverRegistered` as a non-static variable. I could create a pull request with this change, but I don't understand why it was static in the first place.

**Comment by kodeine** [comment]
@Temepest74 can you please submit the PR ?

**Comment by Temepest74** [comment]
Yeah, but it is a good idea to make the variable nonstatic? Whybit was static in the first place?

**Comment by siamak2** [comment]
> Yeah, but it is a good idea to make the variable nonstatic? Whybit was static in the first place?

static variable are declared only once in current session. we need to add only one event listener for saved event so static variable is the best way. if you make it non static the event listener will be registered for every model class you instantiate. for example if you get 1000 model from database and access to their metas then you have 1000 event listener for saved event and every one of them will be called after saving the model and that's not ideal.
can you share your unit test so I can reproduce the problem?

**Comment by kodeine** [comment]
@siamak2 would you mind doing a PR, im not setup at the moment to make changes. And i agree with you of keeping it static.

**Comment by Temepest74** [comment]
Sorry guys, but my timezone didn't match with yours. Thank you @siamak2 , it solved my problem
