### ISSUE TITLE
Can I have a schema ?

### ISSUE THREAD

**Issue by vahidalvandi** [kodeine/laravel-meta#98]
hi 
i have table and i want add same meta in meta table , but i need to user can create manully Her desired meta data . like form builder and in view data can see each meta with label and data saved to db

**Comment by siamak2** [comment]
Hi
You can get all metas using `getMeta()` method without any parameter. it's return value is a `Collection` of all metas where the key is name of the meta. so your view can look something like this:
```blade
@foreach($model->getMeta() as $key => $value)
    <label for="{{$key}}">{{$key}}</label>
    <input id="{{$key}}" value="{{$value}}">
@endforeach
```

**Comment by vahidalvandi** [comment]
Thank you .
How I can manage them with simple ui . Or do you now standard  starter for build meta and forms?

**Comment by siamak2** [comment]
I don't know if any starter pack exists.
You need to create the ui yourself. just loop all metas like the example and add buttons for add new meta and delete this meta.
