### ISSUE TITLE
Eloquent replicate with meta relationship

### ISSUE THREAD

**Issue by stefano-vergani** [kodeine/laravel-meta#99]
Hi, seems eloquent replicate does not replicate meta relation.. I also eager loaded metas relationship.

```
        $newModel = $model->load('metas')->replicate();
        // changing newModel parameters with normal ->attribute ....
        $newModel->save();
```
Expected behavior: model in database is duplicated with some attributes changed and all metas are duplicated too.
Actual behavior: model in database is replicated but no meta saved.

**Comment by siamak2** [comment]
Hi
Laravel meta only uses `metas` relation once and then cache it into another property. By replicating it this cached property no longer exist and laravel meta fills this cache again from `metas` relation.
According to `replicate` [source code](https://github.com/laravel/framework/blob/51b5edaa2f8dfb0acb520ecb394706ade2200a35/src/Illuminate/Database/Eloquent/Model.php#L1616) it just sets current relations results to replicated model and naturally all of the `metas` still have the original model's id and not replicated. This means that existing metas on replicated model belong to the original model.
You can do something like this:
```PHP
$newModel = $model->replicate()->unsetRelation('metas');
$newModel->setMeta( $model->getMeta()->toArray() );
```
